# Generated by Django 5.2.15 on 2026-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Şarkı Adı")),
                ("artist", models.CharField(max_length=200, verbose_name="Sanatçı")),
                (
                    "spotify_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Spotify Linki"
                    ),
                ),
                (
                    "spotify_track_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Spotify Parça ID (embed için)",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(default="🎵", max_length=10, verbose_name="Emoji"),
                ),
                (
                    "mood_tag",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ruh Hali Etiketi"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Şarkı",
                "verbose_name_plural": "Şarkılar",
                "ordering": ["order", "title"],
            },
        ),
    ]
