# Generated by Django 5.2.15 on 2026-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Platform Adı")),
                ("url", models.URLField(verbose_name="Link")),
                (
                    "icon_svg",
                    models.TextField(blank=True, verbose_name="SVG İkon (opsiyonel)"),
                ),
                (
                    "emoji",
                    models.CharField(
                        default="🔗", max_length=10, verbose_name="Emoji İkon"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#b8a9d9", max_length=20, verbose_name="Vurgu Rengi"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kısa Açıklama"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Sosyal Bağlantı",
                "verbose_name_plural": "Sosyal Bağlantılar",
                "ordering": ["order"],
            },
        ),
    ]
