# Generated by Django 5.2.15 on 2026-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InspirationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="inspiration/", verbose_name="Görsel"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Açıklama"
                    ),
                ),
                (
                    "pinterest_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Pinterest Linki"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "İlham Görseli",
                "verbose_name_plural": "İlham Görselleri",
                "ordering": ["order"],
            },
        ),
    ]
