# Generated by Django 5.2.15 on 2026-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Film Adı")),
                ("description", models.TextField(verbose_name="Kısa Açıklama")),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="movies/posters/",
                        verbose_name="Afiş Görseli",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Yıl"
                    ),
                ),
                (
                    "mood_tag",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ruh Hali Etiketi"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Filmler",
                "ordering": ["order", "title"],
            },
        ),
    ]
